export const CREATE_TEMPLATE = "CREATE_TEMPLATE";
export const FETCH_ALL_TEMPLATES = "FETCH_ALL_TEMPLATES";
export const FETCH_SINGLE_TEMPLATE = "FETCH_SINGLE_TEMPLATE";
export const USE_TEMPLATE = "USE_TEMPLATE";
export const DELETE_TEMPLATE = "DELETE_TEMPLATE";
export const EDIT_TEMPLATE = "EDIT_TEMPLATE";
export const LOAD_DEFAULT_TEMPLATES = "LOAD_DEFAULT_TEMPLATES";
export const SEND_MAIL = "SEND_MAIL";
